package com.sodhan.Dynamodb.entity;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "inventory")
public class Inventory {
	
	//@DynamoDBHashKey(attributeName = "itemid")
	@DynamoDBAutoGeneratedKey
	private String itemid;
	@DynamoDBAttribute
	private Item items;
	@DynamoDBAttribute
	private int itemQuantity;
	/*@DynamoDBAttribute
	private Date expiryDate;*/
	@DynamoDBAttribute
	private int price;
	
	@DynamoDBHashKey(attributeName = "itemid")
	public String getItemid() {
		return itemid;
	}
	public void setItemid(String itemid) {
		this.itemid = itemid;
	}
	public Item getItems() {
		return items;
	}
	public void setItems(Item items) {
		this.items = items;
	}
	public int getItemQuantity() {
		return itemQuantity;
	}
	public void setItemQuantity(int itemQuantity) {
		this.itemQuantity = itemQuantity;
	}
	public int getPrice() {
		return price;
	}
	public void setPrice(int price) {
		this.price = price;
	}
	

	
}
